version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: deployment/docker/Dockerfile.server
    ports:
      - "8000:8000"  # Change to 8000:8000, update app.py CMD to --port 8000
    volumes:
      - ./src:/app/src
      - ./templates:/app/templates
      - ./models:/app/models
      - ./configs:/app/configs
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - mlflow
    restart: unless-stopped

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlflow
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri file:///mlflow
    restart: unless-stopped

volumes:
  mlruns: