apiVersion: v1
kind: Service
metadata:
  name: marketing-agent-service
spec:
  selector:
    app: marketing-agent
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer  # Exposes external URL